// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDWNlojJRXQKDGQJD5-GGh68b6WdyHrZtE',
    appId: '1:563841219769:web:a7571082d4fc8c8c3c6f68',
    messagingSenderId: '563841219769',
    projectId: 'music-play-cfc47',
    databaseURL: "https://music-play-cfc47-default-rtdb.firebaseio.com",
    authDomain: 'music-play-cfc47.firebaseapp.com',
    storageBucket: 'music-play-cfc47.appspot.com',
    measurementId: 'G-S0MGVB46MC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA5UCmDldnxqnXBg3tBGZLTOFApdHkL48Y',
    appId: '1:563841219769:android:e3116c0b612dd6053c6f68',
    messagingSenderId: '563841219769',
    projectId: 'music-play-cfc47',
    storageBucket: 'music-play-cfc47.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBbmAus3alqyDxX0RZECegM_8YDxz_fPFU',
    appId: '1:563841219769:ios:ef0d27dfa82e148b3c6f68',
    messagingSenderId: '563841219769',
    projectId: 'music-play-cfc47',
    storageBucket: 'music-play-cfc47.appspot.com',
    iosClientId:
        '563841219769-oimf14ges134ntmoobru5kp3vfi3kd3p.apps.googleusercontent.com',
    iosBundleId: 'com.example.musicPlay',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBbmAus3alqyDxX0RZECegM_8YDxz_fPFU',
    appId: '1:563841219769:ios:05fcf44fe95d04dc3c6f68',
    messagingSenderId: '563841219769',
    projectId: 'music-play-cfc47',
    storageBucket: 'music-play-cfc47.appspot.com',
    iosClientId:
        '563841219769-pmvdjbcsltj57qm5fagp0fabl9nm4lj5.apps.googleusercontent.com',
    iosBundleId: 'com.example.musicPlay.RunnerTests',
  );
}
